---
name: "Dev infra Buils"

on:
  push:
    branches:
      - dev
  repository_dispatch:
    types: [ dev-deploy-event ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Install terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.2

      - name: "Terraform init"
        run: |
           terraform init \
             -backend-config="bucket=${{ secrets.DEV_S3_BUCKET }}" \
             -backend-config="key=terraform.tfstate" \
             -backend-config="region=ap-south-1" \
             -backend-config="access_key=${{ secrets.DEV_ACCESS_KEY }}" \
             -backend-config="secret_key=${{ secrets.DEV_SECRET_KEY }}"

      - name: "terraform validate"
        run: terraform validate 
        
      - name: "terraform fmt"
        run: terraform fmt

      - name: "terraform plan"
        run: terraform plan -var-file=dev.tfvars
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_SECRET_KEY }}
          AWS_REGION: "us-east-1"

      - name: "terraform apply"
        run: terraform apply -auto-approve -var-file=dev.tfvars
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_SECRET_KEY }}
          AWS_REGION: "us-east-1"


